/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadPrescriptionRouteImport } from './routes/upload-prescription'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UploadPrescriptionRoute = UploadPrescriptionRouteImport.update({
  id: '/upload-prescription',
  path: '/upload-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRoute
  '/upload-prescription': typeof UploadPrescriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/medicines'
    | '/upload-prescription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/medicines'
    | '/upload-prescription'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/categories'
    | '/contact'
    | '/login'
    | '/medicines'
    | '/upload-prescription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRoute
  UploadPrescriptionRoute: typeof UploadPrescriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-prescription': {
      id: '/upload-prescription'
      path: '/upload-prescription'
      fullPath: '/upload-prescription'
      preLoaderRoute: typeof UploadPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRoute,
  UploadPrescriptionRoute: UploadPrescriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
